In [1]:
#Numpy - This is a linear algebra library for Python. It can be used to generate data
# Typically we would install this using pip but Jupyter notebook already has it installed
#numby also works with multi dimensional arrray

import numpy as np # You can use np instead of typing numpy with this query

In [2]:
mylist = [1,2,3,4,5]
type(mylist)

list

In [3]:
x = np.array(mylist) #array is like list but its faster. More noticable when using large data. This query converts a list to an array
x

array([1, 2, 3, 4, 5])

In [4]:
type(x)

numpy.ndarray

In [5]:
#numpy array are faster than python list

data = [[1,2,3],[4,5,6],[7,8,9]]
data

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
record = np.array(data) # we can use numpy to convert a nested list to a multi-dimensional array as shown in this query output
record

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# You can use numpy to generate data eg 1 to 1,000,000
#arange() - This generates a range of positive numbers; the last item isn't always included

np.arange(2,10) # This will start from 2 and stop at 9

array([2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [12]:
# generating floating numbers
# generating evenly spaced numbers

#0 - the first number - is where you are starting
#10 - the second number - is where you are stoping and is included
# 6 - the third number -  is how may figures between 0 and 10 should be generated

np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [15]:
# generating random numbers

np.random.rand() # This generates floating random numbers between 0 and 1. 
np.random.rand(3) #If you put a value in the bracket, it generates that number of random numbers
np.random.rand(5,4) # This will generate 5 rows and 4 columns of random numbers

array([[0.62781678, 0.84253617, 0.23032995, 0.90786446],
       [0.64014906, 0.12637971, 0.7153873 , 0.55706062],
       [0.08542825, 0.60854967, 0.67067528, 0.95567197],
       [0.13048472, 0.90455638, 0.76728049, 0.4721723 ],
       [0.52753562, 0.22943315, 0.15593094, 0.77882687]])

In [18]:
#randn will generate random number that can be less than 0 and greater then 1
np.random.randn()
np.random.randn(10)
np.random.randn(10,3)

array([[-0.13157443, -0.10263679,  0.97233613],
       [-0.62759021,  0.36259393, -0.98449143],
       [ 0.15217976, -0.47797624,  0.87280155],
       [-1.60311717,  0.0860173 , -0.30312574],
       [ 0.36416028,  0.11752459, -0.21363622],
       [ 1.47024475, -0.35042776, -0.99450385],
       [ 0.05053009, -1.57166578,  1.83590907],
       [ 0.58434661, -2.56548441, -1.35922463],
       [-0.22264751, -1.61410019,  1.05392108],
       [ 0.7821803 , -0.12407056, -0.52632602]])

In [19]:
np.random.randint(1,4,24).reshape(6,4)

array([[3, 1, 3, 2],
       [2, 3, 2, 1],
       [2, 1, 1, 3],
       [2, 2, 1, 3],
       [3, 3, 1, 1],
       [2, 2, 3, 1]])

In [20]:
# indexing numpy array

x = np.arange(1,26).reshape(5,5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [25]:
x[2][3]

14

In [22]:
x[1]

array([ 6,  7,  8,  9, 10])

In [23]:
x[1][2]

8

In [26]:
x[3][0]

16

In [33]:
#slicing
# bring out 24 and 25

x[4][3:5]

array([24, 25])

In [46]:
# bring out 12, 13, 17, 18

x[2:4]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [48]:
x[2:4,1:3]

array([[12, 13],
       [17, 18]])

In [52]:
# bring out 6,7,11,12

x[1:3,0:2]

array([[ 6,  7],
       [11, 12]])

In [54]:
mylist = [1,2,3,4,5]

In [59]:
# arithmetic with python list

mylist + mylist

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [56]:
np.array(mylist) + np.array(mylist)

array([ 2,  4,  6,  8, 10])

In [57]:
np.array(mylist)

array([1, 2, 3, 4, 5])

In [58]:
# broadcasting 

np.arange(1,10).reshape(3,3) + np.arange(1,4)

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [60]:
 np.arange(1,4)

array([1, 2, 3])

In [61]:
np.arange(1,7).reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [62]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [63]:
x.sum()

325

In [64]:
# sum items by column

x.sum(axis=0)

array([55, 60, 65, 70, 75])

In [65]:
# sum items by row

x.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [66]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [67]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [68]:
np.random.randint(1,10,5)

array([2, 4, 3, 9, 1])

In [69]:
y = np.random.randint(1,10,5) # whenever you run y, the value will change. To fix it, use the query below
y

array([5, 9, 9, 3, 1])

In [74]:
# We use .seed() to freeze the random state of your values

np.random.seed(5) # you must put a number in the bracket beside seed to freeze it or it will keep running random numbers
y = np.random.randint(1,10,5) 
y

array([4, 7, 7, 1, 9])

In [73]:
np.random.seed()
y = np.random.randint(1,10,5) 
y

array([8, 4, 3, 4, 1])

In [76]:
# Comparison operator in numpy

x > 10 # This will check for the values in x and return if they are false or true

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [ ]:
#pandas - Python library for data analysis

#series and dataframe
# series - this is when you work with single columns
# dataframe - this is used when working with multiple columns

In [78]:
sample = np.arange(1,11)
sample

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
# To work with panda, we have to import it

In [80]:
import pandas as pd

In [82]:
# This will return the value and its index position

pd.Series(sample) #series must be capital letter S

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int32

In [84]:
sample = pd.Series(sample)
sample

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int32

In [85]:
sample[8]

9

In [86]:
np.random.randint(100,500,12)

array([328, 331, 212, 258, 308, 107, 304, 499, 213, 180, 127, 144])

In [127]:
df = np.random.randint(100,500,12).reshape(4,3)
df

array([[464, 209, 258],
       [290, 367, 423],
       [480, 283, 487],
       [191, 178, 389]])

In [111]:
pd.DataFrame(data=df) # We use this query to convert the data - df into a data frame. You can then save this into excel to work with

0    1    2
0  127  387  358
1  424  394  205
2  247  374  469
3  345  235  456

In [112]:
pd.DataFrame(data=df, columns=["Jan", "Feb", "Mar"]) # You can also name the columns and index

Jan  Feb  Mar
0  127  387  358
1  424  394  205
2  247  374  469
3  345  235  456

In [114]:
pd.DataFrame(data=df, columns=["Jan", "Feb", "Mar"], index= ["MTN", "UBA", "CNN", "Jumia"])

Jan  Feb  Mar
MTN    127  387  358
UBA    424  394  205
CNN    247  374  469
Jumia  345  235  456

In [128]:
# You can rewrite it as below as well:

months=["Jan", "Feb", "Mar"]
companies=["MTN", "UBA", "CNN", "Jumia"]
pd.DataFrame(data=df, columns=months, index=companies)

Jan  Feb  Mar
MTN    464  209  258
UBA    290  367  423
CNN    480  283  487
Jumia  191  178  389

In [129]:
df.to_csv("demo.csv") # To download to your laptop as csv file named Demo

AttributeError: 'numpy.ndarray' object has no attribute 'to_csv'

In [134]:
#importing data in pandas

# This brings up all the tables in the link

df = pd.read_html("https://en.wikipedia.org/wiki/The_World%27s_Billionaires")
df

[                                                    0  \
 0   List of the world's billionaires, ranked in or...   
 1   The net worth of the world's billionaires incr...   
 2                                 Publication details   
 3                                           Publisher   
 4                                         Publication   
 5                                     First published   
 6                                  Latest publication   
 7                      Current list details (2023)[2]   
 8                                          Wealthiest   
 9                                     Net worth (1st)   
 10                             Number of billionaires   
 11                         Total list net worth value   
 12                                    Number of women   
 13                            New members to the list   
 14           Forbes: The World's Billionaires website   
 
                                                     1  
 0   List of 

In [135]:
# This brings up the second table
df = pd.read_html("https://en.wikipedia.org/wiki/The_World%27s_Billionaires")
df[2]

No.                      Name Net worth (USD)  Age    Nationality  \
0    1  Bernard Arnault & family    $211 billion   74         France   
1    2                 Elon Musk    $180 billion   51  United States   
2    3                Jeff Bezos    $114 billion   59  United States   
3    4             Larry Ellison    $107 billion   78  United States   
4    5            Warren Buffett    $106 billion   92  United States   
5    6                Bill Gates    $104 billion   67  United States   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
8    9             Mukesh Ambani   $83.4 billion   65          India   
9   10             Steve Ballmer   $80.7 billion   67  United States   

          Primary source(s) of wealth  
0                                LVMH  
1                       Tesla, SpaceX  
2                              Amazon  
3                  Oracle Corporation  
4                  Berkshire Hathaway  
5                           Microsoft  
6                      Bloomberg L.P.  
7  Telmex, América Móvil, Grupo Carso  
8                 Reliance Industries  
9                           Microsoft

In [136]:
# Exploratory data analysis (EDA)
# check rows and columns
df[2]. shape

(10, 6)

In [137]:
df = df[2]

In [138]:
df

No.                      Name Net worth (USD)  Age    Nationality  \
0    1  Bernard Arnault & family    $211 billion   74         France   
1    2                 Elon Musk    $180 billion   51  United States   
2    3                Jeff Bezos    $114 billion   59  United States   
3    4             Larry Ellison    $107 billion   78  United States   
4    5            Warren Buffett    $106 billion   92  United States   
5    6                Bill Gates    $104 billion   67  United States   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
8    9             Mukesh Ambani   $83.4 billion   65          India   
9   10             Steve Ballmer   $80.7 billion   67  United States   

          Primary source(s) of wealth  
0                                LVMH  
1                       Tesla, SpaceX  
2                              Amazon  
3                  Oracle Corporation  
4                  Berkshire Hathaway  
5                           Microsoft  
6                      Bloomberg L.P.  
7  Telmex, América Móvil, Grupo Carso  
8                 Reliance Industries  
9                           Microsoft

In [139]:
# Before you start analyzing data, check rows and columns, any missing data. Info will give this information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   No.                          10 non-null     int64 
 1   Name                         10 non-null     object
 2   Net worth (USD)              10 non-null     object
 3   Age                          10 non-null     int64 
 4   Nationality                  10 non-null     object
 5   Primary source(s) of wealth  10 non-null     object
dtypes: int64(2), object(4)
memory usage: 608.0+ bytes


In [140]:
df.describe() # This gives statistical info about your data

No.        Age
count  10.00000  10.000000
mean    5.50000  71.700000
std     3.02765  12.247902
min     1.00000  51.000000
25%     3.25000  65.500000
50%     5.50000  70.500000
75%     7.75000  80.250000
max    10.00000  92.000000

In [141]:
df["Name"] # This will bring out just the name column

0    Bernard Arnault & family
1                   Elon Musk
2                  Jeff Bezos
3               Larry Ellison
4              Warren Buffett
5                  Bill Gates
6           Michael Bloomberg
7        Carlos Slim & family
8               Mukesh Ambani
9               Steve Ballmer
Name: Name, dtype: object

In [143]:
# Accessing multiple columns
# To bring out name and age

df[["Name","Age", "Net worth (USD)"]] # The columns are case sensitive. You must write it exactly as is in the table and must use 2 square brackets

Name  Age Net worth (USD)
0  Bernard Arnault & family   74    $211 billion
1                 Elon Musk   51    $180 billion
2                Jeff Bezos   59    $114 billion
3             Larry Ellison   78    $107 billion
4            Warren Buffett   92    $106 billion
5                Bill Gates   67    $104 billion
6         Michael Bloomberg   81   $94.5 billion
7      Carlos Slim & family   83     $93 billion
8             Mukesh Ambani   65   $83.4 billion
9             Steve Ballmer   67   $80.7 billion

In [144]:
# removing a column
# You use drop for this and have to provide the axis
# column - axis 1, row - axis 0

df.drop("Age", axis=1)

No.                      Name Net worth (USD)    Nationality  \
0    1  Bernard Arnault & family    $211 billion         France   
1    2                 Elon Musk    $180 billion  United States   
2    3                Jeff Bezos    $114 billion  United States   
3    4             Larry Ellison    $107 billion  United States   
4    5            Warren Buffett    $106 billion  United States   
5    6                Bill Gates    $104 billion  United States   
6    7         Michael Bloomberg   $94.5 billion  United States   
7    8      Carlos Slim & family     $93 billion         Mexico   
8    9             Mukesh Ambani   $83.4 billion          India   
9   10             Steve Ballmer   $80.7 billion  United States   

          Primary source(s) of wealth  
0                                LVMH  
1                       Tesla, SpaceX  
2                              Amazon  
3                  Oracle Corporation  
4                  Berkshire Hathaway  
5                           Microsoft  
6                      Bloomberg L.P.  
7  Telmex, América Móvil, Grupo Carso  
8                 Reliance Industries  
9                           Microsoft

In [145]:
# This is not permanently removed so if you run df age will still show

df

No.                      Name Net worth (USD)  Age    Nationality  \
0    1  Bernard Arnault & family    $211 billion   74         France   
1    2                 Elon Musk    $180 billion   51  United States   
2    3                Jeff Bezos    $114 billion   59  United States   
3    4             Larry Ellison    $107 billion   78  United States   
4    5            Warren Buffett    $106 billion   92  United States   
5    6                Bill Gates    $104 billion   67  United States   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
8    9             Mukesh Ambani   $83.4 billion   65          India   
9   10             Steve Ballmer   $80.7 billion   67  United States   

          Primary source(s) of wealth  
0                                LVMH  
1                       Tesla, SpaceX  
2                              Amazon  
3                  Oracle Corporation  
4                  Berkshire Hathaway  
5                           Microsoft  
6                      Bloomberg L.P.  
7  Telmex, América Móvil, Grupo Carso  
8                 Reliance Industries  
9                           Microsoft

In [ ]:
# If you want a permanent delete, you have to save the drop in your df, so it will be:

# df = df.drop("Age", axis=1)

In [146]:
# Removing multiple column
df.drop(["Age", "Nationality"], axis=1)

No.                      Name Net worth (USD)  \
0    1  Bernard Arnault & family    $211 billion   
1    2                 Elon Musk    $180 billion   
2    3                Jeff Bezos    $114 billion   
3    4             Larry Ellison    $107 billion   
4    5            Warren Buffett    $106 billion   
5    6                Bill Gates    $104 billion   
6    7         Michael Bloomberg   $94.5 billion   
7    8      Carlos Slim & family     $93 billion   
8    9             Mukesh Ambani   $83.4 billion   
9   10             Steve Ballmer   $80.7 billion   

          Primary source(s) of wealth  
0                                LVMH  
1                       Tesla, SpaceX  
2                              Amazon  
3                  Oracle Corporation  
4                  Berkshire Hathaway  
5                           Microsoft  
6                      Bloomberg L.P.  
7  Telmex, América Móvil, Grupo Carso  
8                 Reliance Industries  
9                           Microsoft

In [148]:
# Creating a new column

df["Double Age"] = df["Age"] * 2 # This will create a new column called double age, adn will get the age column and multiply it by 2
df

No.                      Name Net worth (USD)  Age    Nationality  \
0    1  Bernard Arnault & family    $211 billion   74         France   
1    2                 Elon Musk    $180 billion   51  United States   
2    3                Jeff Bezos    $114 billion   59  United States   
3    4             Larry Ellison    $107 billion   78  United States   
4    5            Warren Buffett    $106 billion   92  United States   
5    6                Bill Gates    $104 billion   67  United States   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
8    9             Mukesh Ambani   $83.4 billion   65          India   
9   10             Steve Ballmer   $80.7 billion   67  United States   

          Primary source(s) of wealth  Double Age  
0                                LVMH         148  
1                       Tesla, SpaceX         102  
2                              Amazon         118  
3                  Oracle Corporation         156  
4                  Berkshire Hathaway         184  
5                           Microsoft         134  
6                      Bloomberg L.P.         162  
7  Telmex, América Móvil, Grupo Carso         166  
8                 Reliance Industries         130  
9                           Microsoft         134

In [149]:
df

No.                      Name Net worth (USD)  Age    Nationality  \
0    1  Bernard Arnault & family    $211 billion   74         France   
1    2                 Elon Musk    $180 billion   51  United States   
2    3                Jeff Bezos    $114 billion   59  United States   
3    4             Larry Ellison    $107 billion   78  United States   
4    5            Warren Buffett    $106 billion   92  United States   
5    6                Bill Gates    $104 billion   67  United States   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
8    9             Mukesh Ambani   $83.4 billion   65          India   
9   10             Steve Ballmer   $80.7 billion   67  United States   

          Primary source(s) of wealth  Double Age  
0                                LVMH         148  
1                       Tesla, SpaceX         102  
2                              Amazon         118  
3                  Oracle Corporation         156  
4                  Berkshire Hathaway         184  
5                           Microsoft         134  
6                      Bloomberg L.P.         162  
7  Telmex, América Móvil, Grupo Carso         166  
8                 Reliance Industries         130  
9                           Microsoft         134

In [150]:
# renaming columns

df.rename(columns= {"No.":"S/N"})

S/N                      Name Net worth (USD)  Age    Nationality  \
0    1  Bernard Arnault & family    $211 billion   74         France   
1    2                 Elon Musk    $180 billion   51  United States   
2    3                Jeff Bezos    $114 billion   59  United States   
3    4             Larry Ellison    $107 billion   78  United States   
4    5            Warren Buffett    $106 billion   92  United States   
5    6                Bill Gates    $104 billion   67  United States   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
8    9             Mukesh Ambani   $83.4 billion   65          India   
9   10             Steve Ballmer   $80.7 billion   67  United States   

          Primary source(s) of wealth  Double Age  
0                                LVMH         148  
1                       Tesla, SpaceX         102  
2                              Amazon         118  
3                  Oracle Corporation         156  
4                  Berkshire Hathaway         184  
5                           Microsoft         134  
6                      Bloomberg L.P.         162  
7  Telmex, América Móvil, Grupo Carso         166  
8                 Reliance Industries         130  
9                           Microsoft         134

In [151]:
df

No.                      Name Net worth (USD)  Age    Nationality  \
0    1  Bernard Arnault & family    $211 billion   74         France   
1    2                 Elon Musk    $180 billion   51  United States   
2    3                Jeff Bezos    $114 billion   59  United States   
3    4             Larry Ellison    $107 billion   78  United States   
4    5            Warren Buffett    $106 billion   92  United States   
5    6                Bill Gates    $104 billion   67  United States   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
8    9             Mukesh Ambani   $83.4 billion   65          India   
9   10             Steve Ballmer   $80.7 billion   67  United States   

          Primary source(s) of wealth  Double Age  
0                                LVMH         148  
1                       Tesla, SpaceX         102  
2                              Amazon         118  
3                  Oracle Corporation         156  
4                  Berkshire Hathaway         184  
5                           Microsoft         134  
6                      Bloomberg L.P.         162  
7  Telmex, América Móvil, Grupo Carso         166  
8                 Reliance Industries         130  
9                           Microsoft         134

In [152]:
# To make it permanenet, you have to save it in df

df = df.rename(columns= {"No.":"S/N"})
df

S/N                      Name Net worth (USD)  Age    Nationality  \
0    1  Bernard Arnault & family    $211 billion   74         France   
1    2                 Elon Musk    $180 billion   51  United States   
2    3                Jeff Bezos    $114 billion   59  United States   
3    4             Larry Ellison    $107 billion   78  United States   
4    5            Warren Buffett    $106 billion   92  United States   
5    6                Bill Gates    $104 billion   67  United States   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
8    9             Mukesh Ambani   $83.4 billion   65          India   
9   10             Steve Ballmer   $80.7 billion   67  United States   

          Primary source(s) of wealth  Double Age  
0                                LVMH         148  
1                       Tesla, SpaceX         102  
2                              Amazon         118  
3                  Oracle Corporation         156  
4                  Berkshire Hathaway         184  
5                           Microsoft         134  
6                      Bloomberg L.P.         162  
7  Telmex, América Móvil, Grupo Carso         166  
8                 Reliance Industries         130  
9                           Microsoft         134

In [156]:
# working with rows
# with loc, the last one is inlcluded. with iloc, the last one isn't included

df.iloc[1:2]

S/N       Name Net worth (USD)  Age    Nationality  \
1    2  Elon Musk    $180 billion   51  United States   

  Primary source(s) of wealth  Double Age  
1               Tesla, SpaceX         102

In [157]:
df.loc[1:3]

S/N           Name Net worth (USD)  Age    Nationality  \
1    2      Elon Musk    $180 billion   51  United States   
2    3     Jeff Bezos    $114 billion   59  United States   
3    4  Larry Ellison    $107 billion   78  United States   

  Primary source(s) of wealth  Double Age  
1               Tesla, SpaceX         102  
2                      Amazon         118  
3          Oracle Corporation         156

In [158]:
# Dropping a row

df.drop(1,axis=0)

S/N                      Name Net worth (USD)  Age    Nationality  \
0    1  Bernard Arnault & family    $211 billion   74         France   
2    3                Jeff Bezos    $114 billion   59  United States   
3    4             Larry Ellison    $107 billion   78  United States   
4    5            Warren Buffett    $106 billion   92  United States   
5    6                Bill Gates    $104 billion   67  United States   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
8    9             Mukesh Ambani   $83.4 billion   65          India   
9   10             Steve Ballmer   $80.7 billion   67  United States   

          Primary source(s) of wealth  Double Age  
0                                LVMH         148  
2                              Amazon         118  
3                  Oracle Corporation         156  
4                  Berkshire Hathaway         184  
5                           Microsoft         134  
6                      Bloomberg L.P.         162  
7  Telmex, América Móvil, Grupo Carso         166  
8                 Reliance Industries         130  
9                           Microsoft         134

In [160]:
df.append(df)

C:\Users\saluc\AppData\Local\Temp\ipykernel_26760\443893503.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df.append(df)


S/N                      Name Net worth (USD)  Age    Nationality  \
0    1  Bernard Arnault & family    $211 billion   74         France   
1    2                 Elon Musk    $180 billion   51  United States   
2    3                Jeff Bezos    $114 billion   59  United States   
3    4             Larry Ellison    $107 billion   78  United States   
4    5            Warren Buffett    $106 billion   92  United States   
5    6                Bill Gates    $104 billion   67  United States   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
8    9             Mukesh Ambani   $83.4 billion   65          India   
9   10             Steve Ballmer   $80.7 billion   67  United States   
0    1  Bernard Arnault & family    $211 billion   74         France   
1    2                 Elon Musk    $180 billion   51  United States   
2    3                Jeff Bezos    $114 billion   59  United States   
3    4             Larry Ellison    $107 billion   78  United States   
4    5            Warren Buffett    $106 billion   92  United States   
5    6                Bill Gates    $104 billion   67  United States   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
8    9             Mukesh Ambani   $83.4 billion   65          India   
9   10             Steve Ballmer   $80.7 billion   67  United States   

          Primary source(s) of wealth  Double Age  
0                                LVMH         148  
1                       Tesla, SpaceX         102  
2                              Amazon         118  
3                  Oracle Corporation         156  
4                  Berkshire Hathaway         184  
5                           Microsoft         134  
6                      Bloomberg L.P.         162  
7  Telmex, América Móvil, Grupo Carso         166  
8                 Reliance Industries         130  
9                           Microsoft         134  
0                                LVMH         148  
1                       Tesla, SpaceX         102  
2                              Amazon         118  
3                  Oracle Corporation         156  
4                  Berkshire Hathaway         184  
5                           Microsoft         134  
6                      Bloomberg L.P.         162  
7  Telmex, América Móvil, Grupo Carso         166  
8                 Reliance Industries         130  
9                           Microsoft         134

In [161]:
df.append(df, ignore_index=True)

C:\Users\saluc\AppData\Local\Temp\ipykernel_26760\2661378778.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df.append(df, ignore_index=True)


S/N                      Name Net worth (USD)  Age    Nationality  \
0     1  Bernard Arnault & family    $211 billion   74         France   
1     2                 Elon Musk    $180 billion   51  United States   
2     3                Jeff Bezos    $114 billion   59  United States   
3     4             Larry Ellison    $107 billion   78  United States   
4     5            Warren Buffett    $106 billion   92  United States   
5     6                Bill Gates    $104 billion   67  United States   
6     7         Michael Bloomberg   $94.5 billion   81  United States   
7     8      Carlos Slim & family     $93 billion   83         Mexico   
8     9             Mukesh Ambani   $83.4 billion   65          India   
9    10             Steve Ballmer   $80.7 billion   67  United States   
10    1  Bernard Arnault & family    $211 billion   74         France   
11    2                 Elon Musk    $180 billion   51  United States   
12    3                Jeff Bezos    $114 billion   59  United States   
13    4             Larry Ellison    $107 billion   78  United States   
14    5            Warren Buffett    $106 billion   92  United States   
15    6                Bill Gates    $104 billion   67  United States   
16    7         Michael Bloomberg   $94.5 billion   81  United States   
17    8      Carlos Slim & family     $93 billion   83         Mexico   
18    9             Mukesh Ambani   $83.4 billion   65          India   
19   10             Steve Ballmer   $80.7 billion   67  United States   

           Primary source(s) of wealth  Double Age  
0                                 LVMH         148  
1                        Tesla, SpaceX         102  
2                               Amazon         118  
3                   Oracle Corporation         156  
4                   Berkshire Hathaway         184  
5                            Microsoft         134  
6                       Bloomberg L.P.         162  
7   Telmex, América Móvil, Grupo Carso         166  
8                  Reliance Industries         130  
9                            Microsoft         134  
10                                LVMH         148  
11                       Tesla, SpaceX         102  
12                              Amazon         118  
13                  Oracle Corporation         156  
14                  Berkshire Hathaway         184  
15                           Microsoft         134  
16                      Bloomberg L.P.         162  
17  Telmex, América Móvil, Grupo Carso         166  
18                 Reliance Industries         130  
19                           Microsoft         134

In [162]:
# sorting data

df.sort_values(by="Age")

S/N                      Name Net worth (USD)  Age    Nationality  \
1    2                 Elon Musk    $180 billion   51  United States   
2    3                Jeff Bezos    $114 billion   59  United States   
8    9             Mukesh Ambani   $83.4 billion   65          India   
5    6                Bill Gates    $104 billion   67  United States   
9   10             Steve Ballmer   $80.7 billion   67  United States   
0    1  Bernard Arnault & family    $211 billion   74         France   
3    4             Larry Ellison    $107 billion   78  United States   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
4    5            Warren Buffett    $106 billion   92  United States   

          Primary source(s) of wealth  Double Age  
1                       Tesla, SpaceX         102  
2                              Amazon         118  
8                 Reliance Industries         130  
5                           Microsoft         134  
9                           Microsoft         134  
0                                LVMH         148  
3                  Oracle Corporation         156  
6                      Bloomberg L.P.         162  
7  Telmex, América Móvil, Grupo Carso         166  
4                  Berkshire Hathaway         184

In [163]:
df.sort_values(by="Name")

S/N                      Name Net worth (USD)  Age    Nationality  \
0    1  Bernard Arnault & family    $211 billion   74         France   
5    6                Bill Gates    $104 billion   67  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
1    2                 Elon Musk    $180 billion   51  United States   
2    3                Jeff Bezos    $114 billion   59  United States   
3    4             Larry Ellison    $107 billion   78  United States   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
8    9             Mukesh Ambani   $83.4 billion   65          India   
9   10             Steve Ballmer   $80.7 billion   67  United States   
4    5            Warren Buffett    $106 billion   92  United States   

          Primary source(s) of wealth  Double Age  
0                                LVMH         148  
5                           Microsoft         134  
7  Telmex, América Móvil, Grupo Carso         166  
1                       Tesla, SpaceX         102  
2                              Amazon         118  
3                  Oracle Corporation         156  
6                      Bloomberg L.P.         162  
8                 Reliance Industries         130  
9                           Microsoft         134  
4                  Berkshire Hathaway         184

In [164]:
df.sort_values(by="Name", ascending = False) # sort in desc order

S/N                      Name Net worth (USD)  Age    Nationality  \
4    5            Warren Buffett    $106 billion   92  United States   
9   10             Steve Ballmer   $80.7 billion   67  United States   
8    9             Mukesh Ambani   $83.4 billion   65          India   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
3    4             Larry Ellison    $107 billion   78  United States   
2    3                Jeff Bezos    $114 billion   59  United States   
1    2                 Elon Musk    $180 billion   51  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
5    6                Bill Gates    $104 billion   67  United States   
0    1  Bernard Arnault & family    $211 billion   74         France   

          Primary source(s) of wealth  Double Age  
4                  Berkshire Hathaway         184  
9                           Microsoft         134  
8                 Reliance Industries         130  
6                      Bloomberg L.P.         162  
3                  Oracle Corporation         156  
2                              Amazon         118  
1                       Tesla, SpaceX         102  
7  Telmex, América Móvil, Grupo Carso         166  
5                           Microsoft         134  
0                                LVMH         148

In [165]:
# filtering data

df["Age"] > 60

0     True
1    False
2    False
3     True
4     True
5     True
6     True
7     True
8     True
9     True
Name: Age, dtype: bool

In [166]:
df["Nationality"] != "United States"

0     True
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8     True
9    False
Name: Nationality, dtype: bool

In [167]:
# If you want to see the data

df[df["Nationality"] != "United States"]

S/N                      Name Net worth (USD)  Age Nationality  \
0    1  Bernard Arnault & family    $211 billion   74      France   
7    8      Carlos Slim & family     $93 billion   83      Mexico   
8    9             Mukesh Ambani   $83.4 billion   65       India   

          Primary source(s) of wealth  Double Age  
0                                LVMH         148  
7  Telmex, América Móvil, Grupo Carso         166  
8                 Reliance Industries         130

In [170]:
# | is or; while & is and

df[(df["Nationality"] != "United States") | (df["Age"] > 60)]

S/N                      Name Net worth (USD)  Age    Nationality  \
0    1  Bernard Arnault & family    $211 billion   74         France   
3    4             Larry Ellison    $107 billion   78  United States   
4    5            Warren Buffett    $106 billion   92  United States   
5    6                Bill Gates    $104 billion   67  United States   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
8    9             Mukesh Ambani   $83.4 billion   65          India   
9   10             Steve Ballmer   $80.7 billion   67  United States   

          Primary source(s) of wealth  Double Age  
0                                LVMH         148  
3                  Oracle Corporation         156  
4                  Berkshire Hathaway         184  
5                           Microsoft         134  
6                      Bloomberg L.P.         162  
7  Telmex, América Móvil, Grupo Carso         166  
8                 Reliance Industries         130  
9                           Microsoft         134

In [171]:
df[(df["Nationality"] != "United States") & (df["Age"] > 60)]

S/N                      Name Net worth (USD)  Age Nationality  \
0    1  Bernard Arnault & family    $211 billion   74      France   
7    8      Carlos Slim & family     $93 billion   83      Mexico   
8    9             Mukesh Ambani   $83.4 billion   65       India   

          Primary source(s) of wealth  Double Age  
0                                LVMH         148  
7  Telmex, América Móvil, Grupo Carso         166  
8                 Reliance Industries         130

In [173]:
df[df["Nationality"].isin(["India"])]

S/N           Name Net worth (USD)  Age Nationality  \
8    9  Mukesh Ambani   $83.4 billion   65       India   

  Primary source(s) of wealth  Double Age  
8         Reliance Industries         130

In [174]:
df[df["Nationality"].isin(["India", "Mexico"])] # easier to check for multiple countries

S/N                  Name Net worth (USD)  Age Nationality  \
7    8  Carlos Slim & family     $93 billion   83      Mexico   
8    9         Mukesh Ambani   $83.4 billion   65       India   

          Primary source(s) of wealth  Double Age  
7  Telmex, América Móvil, Grupo Carso         166  
8                 Reliance Industries         130

In [175]:
#useful functions
# each name will come is as x, as it comes in its split and we pick position 0

def firstname(x):
    return x.split()[0]

In [176]:
firstname("Wale Olajumoke")

'Wale'

In [177]:
firstname("Elon Musk")

'Elon'

In [178]:
df["firstname"] = df["Name"].apply(firstname)
df

S/N                      Name Net worth (USD)  Age    Nationality  \
0    1  Bernard Arnault & family    $211 billion   74         France   
1    2                 Elon Musk    $180 billion   51  United States   
2    3                Jeff Bezos    $114 billion   59  United States   
3    4             Larry Ellison    $107 billion   78  United States   
4    5            Warren Buffett    $106 billion   92  United States   
5    6                Bill Gates    $104 billion   67  United States   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
8    9             Mukesh Ambani   $83.4 billion   65          India   
9   10             Steve Ballmer   $80.7 billion   67  United States   

          Primary source(s) of wealth  Double Age firstname  
0                                LVMH         148   Bernard  
1                       Tesla, SpaceX         102      Elon  
2                              Amazon         118      Jeff  
3                  Oracle Corporation         156     Larry  
4                  Berkshire Hathaway         184    Warren  
5                           Microsoft         134      Bill  
6                      Bloomberg L.P.         162   Michael  
7  Telmex, América Móvil, Grupo Carso         166    Carlos  
8                 Reliance Industries         130    Mukesh  
9                           Microsoft         134     Steve

In [179]:
def lastname(x):
    return x.split()[1]

In [180]:
lastname("Wale Olajumoke")

'Olajumoke'

In [181]:
lastname("Elon Musk")

'Musk'

In [183]:
df["Last name"] = df["Name"].apply(lastname)
df

S/N                      Name Net worth (USD)  Age    Nationality  \
0    1  Bernard Arnault & family    $211 billion   74         France   
1    2                 Elon Musk    $180 billion   51  United States   
2    3                Jeff Bezos    $114 billion   59  United States   
3    4             Larry Ellison    $107 billion   78  United States   
4    5            Warren Buffett    $106 billion   92  United States   
5    6                Bill Gates    $104 billion   67  United States   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
8    9             Mukesh Ambani   $83.4 billion   65          India   
9   10             Steve Ballmer   $80.7 billion   67  United States   

          Primary source(s) of wealth  Double Age firstname  Last name  
0                                LVMH         148   Bernard    Arnault  
1                       Tesla, SpaceX         102      Elon       Musk  
2                              Amazon         118      Jeff      Bezos  
3                  Oracle Corporation         156     Larry    Ellison  
4                  Berkshire Hathaway         184    Warren    Buffett  
5                           Microsoft         134      Bill      Gates  
6                      Bloomberg L.P.         162   Michael  Bloomberg  
7  Telmex, América Móvil, Grupo Carso         166    Carlos       Slim  
8                 Reliance Industries         130    Mukesh     Ambani  
9                           Microsoft         134     Steve    Ballmer

In [184]:
# To show first 5 rows

df.head()

S/N                      Name Net worth (USD)  Age    Nationality  \
0    1  Bernard Arnault & family    $211 billion   74         France   
1    2                 Elon Musk    $180 billion   51  United States   
2    3                Jeff Bezos    $114 billion   59  United States   
3    4             Larry Ellison    $107 billion   78  United States   
4    5            Warren Buffett    $106 billion   92  United States   

  Primary source(s) of wealth  Double Age firstname Last name  
0                        LVMH         148   Bernard   Arnault  
1               Tesla, SpaceX         102      Elon      Musk  
2                      Amazon         118      Jeff     Bezos  
3          Oracle Corporation         156     Larry   Ellison  
4          Berkshire Hathaway         184    Warren   Buffett

In [185]:
# last 5 rows

df.tail()

S/N                  Name Net worth (USD)  Age    Nationality  \
5    6            Bill Gates    $104 billion   67  United States   
6    7     Michael Bloomberg   $94.5 billion   81  United States   
7    8  Carlos Slim & family     $93 billion   83         Mexico   
8    9         Mukesh Ambani   $83.4 billion   65          India   
9   10         Steve Ballmer   $80.7 billion   67  United States   

          Primary source(s) of wealth  Double Age firstname  Last name  
5                           Microsoft         134      Bill      Gates  
6                      Bloomberg L.P.         162   Michael  Bloomberg  
7  Telmex, América Móvil, Grupo Carso         166    Carlos       Slim  
8                 Reliance Industries         130    Mukesh     Ambani  
9                           Microsoft         134     Steve    Ballmer

In [186]:
df.value_counts("Nationality") #This is very valuable to know. It helps count values for each item in your column

Nationality
United States    7
France           1
India            1
Mexico           1
dtype: int64

In [187]:
df["Nationality"].unique() # This will give the unique values in your data column

array(['France', 'United States', 'Mexico', 'India'], dtype=object)

In [188]:
# To count the number of unique values in the column

df["Nationality"].nunique()

4

In [189]:
# Find the top 3 richest billionaires in the data

df.head(3)

S/N                      Name Net worth (USD)  Age    Nationality  \
0    1  Bernard Arnault & family    $211 billion   74         France   
1    2                 Elon Musk    $180 billion   51  United States   
2    3                Jeff Bezos    $114 billion   59  United States   

  Primary source(s) of wealth  Double Age firstname Last name  
0                        LVMH         148   Bernard   Arnault  
1               Tesla, SpaceX         102      Elon      Musk  
2                      Amazon         118      Jeff     Bezos

In [190]:
# Find top 3 oldest billionaires in the data

df["Age"].sort_values(ascending = False).head(3)

4    92
7    83
6    81
Name: Age, dtype: int64

In [193]:
df.sort_values(by="Age", ascending=False).head(3)

S/N                  Name Net worth (USD)  Age    Nationality  \
4    5        Warren Buffett    $106 billion   92  United States   
7    8  Carlos Slim & family     $93 billion   83         Mexico   
6    7     Michael Bloomberg   $94.5 billion   81  United States   

          Primary source(s) of wealth  Double Age firstname  Last name  
4                  Berkshire Hathaway         184    Warren    Buffett  
7  Telmex, América Móvil, Grupo Carso         166    Carlos       Slim  
6                      Bloomberg L.P.         162   Michael  Bloomberg

In [194]:
df.sort_values(by="Age", ascending=False)[:3]

S/N                  Name Net worth (USD)  Age    Nationality  \
4    5        Warren Buffett    $106 billion   92  United States   
7    8  Carlos Slim & family     $93 billion   83         Mexico   
6    7     Michael Bloomberg   $94.5 billion   81  United States   

          Primary source(s) of wealth  Double Age firstname  Last name  
4                  Berkshire Hathaway         184    Warren    Buffett  
7  Telmex, América Móvil, Grupo Carso         166    Carlos       Slim  
6                      Bloomberg L.P.         162   Michael  Bloomberg

In [195]:
# To replace United states with USA

df["Nationality"].replace(to_replace="United States", value="USA")

0    France
1       USA
2       USA
3       USA
4       USA
5       USA
6       USA
7    Mexico
8     India
9       USA
Name: Nationality, dtype: object

In [196]:
# to make it permanent
df["Nationality"] = df["Nationality"].replace(to_replace="United States", value="USA")
df

S/N                      Name Net worth (USD)  Age Nationality  \
0    1  Bernard Arnault & family    $211 billion   74      France   
1    2                 Elon Musk    $180 billion   51         USA   
2    3                Jeff Bezos    $114 billion   59         USA   
3    4             Larry Ellison    $107 billion   78         USA   
4    5            Warren Buffett    $106 billion   92         USA   
5    6                Bill Gates    $104 billion   67         USA   
6    7         Michael Bloomberg   $94.5 billion   81         USA   
7    8      Carlos Slim & family     $93 billion   83      Mexico   
8    9             Mukesh Ambani   $83.4 billion   65       India   
9   10             Steve Ballmer   $80.7 billion   67         USA   

          Primary source(s) of wealth  Double Age firstname  Last name  
0                                LVMH         148   Bernard    Arnault  
1                       Tesla, SpaceX         102      Elon       Musk  
2                              Amazon         118      Jeff      Bezos  
3                  Oracle Corporation         156     Larry    Ellison  
4                  Berkshire Hathaway         184    Warren    Buffett  
5                           Microsoft         134      Bill      Gates  
6                      Bloomberg L.P.         162   Michael  Bloomberg  
7  Telmex, América Móvil, Grupo Carso         166    Carlos       Slim  
8                 Reliance Industries         130    Mukesh     Ambani  
9                           Microsoft         134     Steve    Ballmer

In [ ]:
# handling missing data

